module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/Niko-AND-Janiya/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94742531391",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": true ,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": false ,
  "ANTI_LINK": false ,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "DABIYA",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": true ,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false
};
